/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(() => {
        const savedLanguage = localStorage.getItem('language');
        return savedLanguage ? savedLanguage : 'he';
    });

    // Set initial language based on browser preference if needed
    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'he' ? 'rtl' : 'ltr';
    }, [language]);

    const translations = {
        he: {
            // Header
            'programs': 'תוכניות',
            'lets_talk': 'בואו נדבר',
            'mobile_menu': 'תפריט',

            // Hero
            'hero_title': 'ברק אלוני',
            'hero_subtitle': 'סדנאות כלבנות והעצמה',
            'hero_description': 'חינוך, קהילה וארגונים. נבנה יחד חוויה מעצימה, ערכית ומחברת - עם מעל 10 שנות ניסיון בשטח.',
            'who_is_it_for': 'למי זה מתאים?',
            'experience': '+10 שנות ניסיון',
            'nationwide': 'פריסה ארצית',
            'all_ages': 'מותאם לכל גיל ואוכלוסייה',
            'video_title': 'סרטון תדמית - ברק אלוני',

            // Programs
            'our_programs': 'התוכניות שלנו',
            'tailored_solutions': 'פתרונות מותאמים אישית',
            'for_education': 'למסגרות חינוך וארגונים',
            'program_education_title': 'גפ"ן / מוסדות חינוך',
            'program_education_content': 'תוכנית תהליכית לתלמידים מכיתות א\' - י"ב, המותאמת לחינוך רגיל, חינוך מיוחד, נוער בסיכון, עולים חדשים ועוד. אנו מעניקים מענה תומך ומשלים לתהליכים החינוכיים המתקיימים במסגרת בית הספר.',
            'program_events_title': 'סדנאות ואירועים חד-פעמיים',
            'program_events_content': 'פעילויות חווייתיות מלאות אנרגיה המתאימות ל: ימי הולדת, קייטנות, סדנאות גיבוש ועוד! הכלבים והצוות שלנו מביאים שמחה, למידה ותחושת העצמה אישית לכל המשתתפים.',
            'program_special_title': 'אוכלוסיות מיוחדות',
            'program_special_content': 'התאמות ייעודיות עבור אוכלוסיות שונות כמו: PTSD, קשישים, נוער בסיכון, מרכזי יום ועוד. אנו משלבים כלים מעצימים, ועבודה קבוצתית שמחזקת אמון ואת תחושת ביטחון.',
            'more_details': 'לפרטים נוספים',
            'watch_video': 'צפה בסרטון',

            // Contact
            'contact_title': 'צרו קשר',
            'contact_subtitle': 'רוצים לשמוע עוד? \nאנחנו זמינים לכל שאלה, התייעצות או בקשה.',
            'who_we_are': 'עם מי מדברים?',
            'barak_aloni': 'ברק אלוני',
            'email': 'אימייל',
            'area': 'אזור פעילות',
            'follow_us': 'עקבו אחרינו',
            'full_name': 'שם מלא',
            'phone_label': 'טלפון',
            'email_label': 'אימייל',
            'message_optional': 'הודעה (אופציונלי)',
            'message_placeholder': 'היי, אשמח לשמוע פרטים על...',
            'send_details': 'שלחו פרטים',
            'privacy_note': '* הנתונים נשלחים ישירות למייל שלנו ולא מועברים לצד ג\'.',
            'whatsapp_message': 'אשמח לשמוע עוד פרטים על השירותים שלכם',
            'name_placeholder': 'ישראל ישראלי',
            'phone_placeholder': '050-0000000',
            'email_placeholder': 'your@email.com',

            // Footer
            'accessibility_statement': 'הצהרת נגישות',
            'privacy_policy': 'מדיניות פרטיות',
            'rights_reserved': '© כל הזכויות באתר זה שמורות לברק אלוני 2024. אין להעתיק, לשכפל ולצלם.',
            'copyright': '© כל הזכויות באתר זה שמורות לברק אלוני {year}. אין להעתיק, לשכפל ולצלם.',

            // Program Modal
            'program_modal_title': 'גפ"ן / מוסדות חינוך',
            'therapeutic_dog_training': 'הדרכת כלבנות טיפולית',
            'gefen_approved': 'תוכנית מאושרת גפ"ן',
            'program_intro': 'התוכנית הינה תוכנית חינוכית המשלבת בין עולם הכלבנות לבין עולם ההתפתחות האישית. התוכנית נועדה לפתח מיומנויות חברתיות, תקשורת וביטחון עצמי אצל התלמידים.',
            'program_goals_title': 'מטרות התוכנית',
            'program_goal_1': 'העצמה אישית וקבוצתית',
            'program_goal_1_desc': 'דרך העבודה החווייתית, בה הכלבים משמשים כמראה לחיים עצמם, התלמידים מפתחים תחושת מסוגלות, בונים דימוי עצמי חיובי ולומדים לעבוד בשיתוף פעולה.',
            'program_goal_2': 'קבלת האחר וקבלה עצמית',
            'program_goal_2_desc': 'הכלב מקבל כל תלמיד ללא תנאי וללא שיפוטיות, מה שמאפשר לתלמידים ללמוד לקבל את עצמם ואת השונים מהם בסביבה תומכת.',
            'program_goal_3': 'חיזוק ופיתוח כישורי חיים',
            'program_goal_3_desc': 'התוכנית מקנה מיומנויות חשובות כמו סבלנות, הצבת גבולות ואחריות אישית שמתורגמות לחיי היומיום בכיתה ומחוצה לה.',
            'program_goal_4': 'התגברות על פחדים',
            'program_goal_4_desc': 'המפגש ההדרגתי והמונחה עם הכלבים מעניק לתלמידים סביבה בטוחה להתמודד עם פחדים ומחסומים החשובים לביטחונו האישי.',
            'program_goal_5': 'חיזוק מעורבות חברתית',
            'program_goal_5_desc': 'העבודה בקבוצה יוצרת תחושת שייכות, מעודדת עזרה הדדית ומובילה למעורבות פעילה וחיובית יותר בחיי בית הספר.',
            'program_goal_6': 'חיבור חברתי במסגרת החינוכית',
            'program_goal_6_desc': 'הכלבים משמשים כגשר ליצירת חיבורים חברתיים בין תלמידים, תורמים לגיבוש הכיתה ונותנים להם כלים להתגבר על אתגרים חברתיים ורגשיים יחד.',
            'program_targets_title': 'יעדים וערכים',
            'program_target_1': 'יצירת סביבה חינוכית בטוחה',
            'program_target_2': 'דיונים ללא שיפוטיות',
            'program_target_3': 'הבעת דעות ללא חשש',
            'program_target_4': 'לקיחת אחריות אישית',
            'program_target_5': 'השתתפות מתוך רצון ובחירה',
            'target_audience_title': 'קהל היעד',
            'target_audience_content': 'התוכנית מיועדת לתלמידים מכיתה <span className="font-bold text-gray-900">א\' ועד י"ב</span> מכל המגזרים. \nמותאמת למגוון רחב של אוכלוסיות: מצטיינים, מחוננים, חינוך מיוחד, נוער בסיכון, הפרעות קשב, לקויות למידה, עולים חדשים וכו\'.',
            'methods_title': 'דרכי פעולה',
            'methods_content_1': 'דרך עולם הכלבנות נלמד תקשורת אפקטיבית, שפת גוף, אילוף בסיסי, ספורט כלבני וכלבי שירות. ההדרכה מתבצעת "בגובה העיניים" תוך יצירת אמון ומחויבות הדדית.',
            'methods_content_2': 'הקבוצות הינן קבועות (ללא חילופי תלמידים) כדי לשמור על מרחב בטוח ואינטימי. אנו מבצעים מעקב אישי אחר כל תלמיד כדי לדייק את המענה.',
            'expected_results_title': 'תוצאות מצופות',
            'result_1': 'ביטחון עצמי וחברתי',
            'result_2': 'יצירת קשרים חברתיים',
            'result_3': 'פיתוח אמפתיה וחמלה',
            'result_4': 'מוסריות כלפי בעלי חיים',
            'technical_details_title': 'פרטים טכניים:',
            'group_size': '• גודל קבוצה: 6-8 תלמידים',
            'requirements': '• דרישות: כיתה קבועה, ליווי ייעוץ חינוכי מטעם המוסד',
            'contact_details_modal': '• פרטי קשר: ברק אלוני | 050-8391268 | Dogs@barakaloni.com',

            // Accessibility Widget
            'accessibility_tools': 'כלי נגישות',
            'grayscale': 'גווני אפור',
            'invert_contrast': 'ניגודיות הפוכה',
            'decrease_text': 'הקטנת טקסט',
            'increase_text': 'הגדלת טקסט',
            'highlight_headings': 'הדגשת כותרות',
            'highlight_links': 'הדגשת קישורים',
            'readable_font': 'גופן קריא',
            'big_cursor': 'סמן גדול',
            'stop_animations': 'עצירת אנימציות',
            'reset_settings': 'איפוס הגדרות',

            // Cookie Banner
            'cookies_title': 'אנחנו משתמשים בעוגיות',
            'cookies_text': 'האתר משתמש בעוגיות כדי לשפר את חווית הגלישה. המשך הגלישה באתר מהווה הסכמה לשימוש זה.',
            'learn_more': 'למידע נוסף',
            'got_it': 'הבנתי, תודה',

            // Legal Modal
            'legal_info': 'מידע משפטי',
            'accessibility_intro': 'אנו בברק אלוני רואים חשיבות עליונה במתן שירות שוויוני לכלל הלקוחות והגולשים ובשיפור השירות הניתן ללקוחות עם מוגבלות.',
            'accessibility_resources': 'בהתאם לכך, אנו משקיעים משאבים רבים בהנגשת האתר שלנו, במטרה לאפשר למרבית האוכלוסייה לגלוש בו בקלות ובנוחות וליהנות מהשירותים ומהתכנים המתפרסמים בו.',
            'accessibility_level': 'רמת הנגישות',
            'accessibility_standard': 'האתר נבנה בהתאם לתקנות שוויון זכויות לאנשים עם מוגבלות (התאמות נגישות לשירות), תשע"ג-2013, ולתקן הישראלי ת"י 5568 לנגישות תכנים באינטרנט ברמת AA.',
            'adjustments_made': 'התאמות שבוצעו באתר',
            'adjustment_1': 'האתר מותאם לצפייה בדפדפנים הנפוצים (Chrome, Firefox, Safari, Edge).',
            'adjustment_2': 'תכני האתר כתובים בשפה ברורה וקריאה.',
            'adjustment_3': 'מבנה האתר מושתת על ניווט נוח וברור ותפריטים הבנויים באמצעות רשימות המאפשרים התמצאות קלה ופשוטה.',
            'adjustment_4': 'האתר מותאם לגלישה במכשירים ניידים (רספונסיבי).',
            'adjustment_5': 'התמונות באתר כוללות תיאור טקסטואלי חלופי (Alt Text).',
            'adjustment_6': 'האתר מאפשר שינוי גודל הגופן על ידי שימוש במקלדת (Ctrl + / -).',
            'accessibility_contact_title': 'יצירת קשר בנושא נגישות',
            'accessibility_contact_text': 'אם נתקלתם בקושי כלשהו בגלישה באתר או שיש לכם הערה בנושא, נשמח אם תצרו איתנו קשר כדי שנוכל לטפל בבעיה:',
            'accessibility_email': 'אימייל: dogs@barakaloni.com',
            'accessibility_phone': 'טלפון: 050-8391-268',
            'privacy_intro': 'אנו מכבדים את פרטיות המשתמשים באתר ומחויבים להגן על המידע האישי שאתם משתפים איתנו.',
            'data_collection': 'איסוף מידע',
            'data_collection_text': 'כאשר אתם משאירים פרטים באתר (שם, טלפון, אימייל) לצורך יצירת קשר, אנו אוספים את המידע הזה אך ורק למטרת חזרה אליכם ומתן שירות.',
            'data_use': 'שימוש במידע',
            'data_use_text': 'המידע שנאסף לא יועבר לצדדים שלישיים ללא הסכמתכם, אלא אם כן נדרשנו לכך על פי חוק.',
            'cookies_policy_title': 'עוגיות (Cookies)',
            'cookies_policy_text_1': 'האתר עשוי להשתמש ב"עוגיות" (Cookies) לצורך תפעולו השוטף והתקין, ובכלל זה כדי לאסוף נתונים סטטיסטיים אודות השימוש באתר, לאימות פרטים, וכדי להתאים את האתר להעדפותיכם האישיות.',
            'cookies_policy_text_2': 'דפדפנים מודרניים מאפשרים לכם להימנע מקבלת Cookies. אם אינכם יודעים כיצד לעשות זאת, בדקו בקובץ העזרה של הדפדפן שבו אתם משתמשים.',
            // User Menu
            'profile': 'פרופיל',
            'my_applications': 'הגשות המועמדות שלי',
            'admin_dashboard': 'לוח בקרה מנהל',
            'recruiter_dashboard': 'לוח בקרה מגייס',
            'sign_out': 'התנתק',
            'admin_role': 'מנהל',
            'recruiter_role': 'מגייס',

            // Manager & Dashboard Translations
            'mission_control': 'מרכז שליטה',
            'analytics_dashboard_sub': 'לוח בקרה ואנליטיקס',
            'uptime': 'זמן פעילות',
            'home_website': 'לאתר הבית',
            'all_pages': 'כל הדפים',
            'online': 'מחוברים',
            'overview': 'סקירה כללית',
            'traffic': 'תעבורה',
            'content': 'תוכן',
            'geo': 'מיקום ומכשירים',
            'feed': 'פעילות בזמן אמת',
            'jobs': 'משרות',
            'users': 'משתמשים',
            'unique_30d': 'מבקרים ייחודיים (30 יום)',
            'views_24h': 'צפיות (24 שעות)',
            'videos_24h': 'סרטונים (24 שעות)',
            'contacts_24h': 'יצירת קשר (24 שעות)',
            'whatsapp_24h': 'ווטסאפ (24 שעות)',
            'conversion_funnel': 'משפך המרות',
            'funnel_sub': 'מסע המבקר ב-30 הימים האחרונים',
            'visitors': 'מבקרים',
            'video_plays': 'צפיות בסרטון',
            'contact_clicks': 'קליקים ליצירת קשר',
            'whatsapp': 'ווטסאפ',
            'form_submits': 'שליחת טפסים',
            'traffic_growth': 'צמיחת תעבורה',
            'traffic_sub': 'ייחודיים מול סה"כ (30 יום)',
            'page_views': 'צפיות בדפים',
            'unique_people': 'אנשים ייחודיים',
            'peak_hours': 'שעות שיא',
            'peak_hours_sub': 'מתי מגיעים המבקרים',
            'by_day_of_week': 'לפי ימי השבוע',
            'per_page_traffic': 'תעבורה לפי דף',
            'per_page_sub': 'ביקורים יומיים לפי דף (30 יום)',
            'source_trends': 'מגמות מקורות תנועה',
            'source_trends_sub': 'מאיפה מגיעה התנועה (יומי)',
            'return_vs_new': 'מבקרים חוזרים מול חדשים',
            'return_vs_new_sub': 'פירוט יומי (30 יום)',
            'new': 'חדשים',
            'returning': 'חוזרים',
            'top_sources_30d': 'מקורות מובילים (30 יום)',
            'direct_bookmark': 'ישיר / סימניה',
            'no_data_yet': 'אין נתונים עדיין.',
            'utm_campaigns_90d': 'קמפיינים UTM (90 יום)',
            'no_utm_data': 'אין נתוני UTM עדיין. הוסיפו ?utm_source=... לקישורים שלכם.',
            'video_views': 'צפיות בסרטונים',
            'no_video_data': 'אין עדיין נתוני צפייה בסרטונים',
            'video_data_sub': 'אירועי צפייה בסרטונים יופיעו כאן כגרפים נפרדים ברגע שמבקרים יתחילו לצפות בסרטונים.',
            'scroll_depth': 'עומק גלילה',
            'scroll_depth_sub': 'אחוז גלילה ממוצע לפי דף',
            'time_per_page': 'זמן לפי דף',
            'time_per_page_sub': 'משך זמן ממוצע לסשן',
            'lang_bounce': 'שפה ואחוז נטישה',
            'bounce_by_page': 'שיעור נטישה לפי דף',
            'contact_channels': 'ערוצי יצירת קשר',
            'contact_channels_sub': 'קליקים לווטסאפ מול יצירת קשר',
            'top_content': 'תוכן מוביל',
            'top_countries': 'מדינות מובילות',
            'visitor_origins_sub': 'מקורות המבקרים (30 יום)',
            'top_cities': 'ערים מובילות',
            'devices_browsers': 'מכשירים ודפדפנים',
            'device_sub': 'פירוט לפי סוג מכשיר (מחשב/נייד)',
            'browsers': 'דפדפנים',
            'operating_systems': 'מערכות הפעלה',
            'activity_log': 'יומן פעילות',
            'activity_sub': 'זרם פעולות בזמן אמת',
            'all_events': 'כל האירועים',
            'no_logs': 'אין יומני פעילות זמינים.',

            // User Roles
            'role_guidelines_title': 'מדריך תפקידי משתמשים',
            'role_guidelines_sub': 'הסבר על מה כל תפקיד במערכת יכול לבצע:',
            'role_admin_desc': 'בעל הרשאות מלאות. יכול לצפות באנליטיקס, לנהל משתמשים ותפקידים, לחסום/לשחרר משתמשים, ליצור ולערוך משרות, ולנהל את כל הגשות המועמדות.',
            'role_recruiter_desc': 'הרשאות גיוס. יכול ליצור ולערוך משרות ולצפות במועמדים שהגישו אליהן מועמדות. אין גישה לנתוני אנליטיקס או לרשימת המשתמשים הכללית.',
            'role_user_desc': 'מועמד/ת או אורח/ת. יכול לצפות בלוח המשרות, להגיש מועמדות, להעלות קובץ קורות חיים (CV), לערוך את הפרופיל האישי ולעקוב אחר סטטוס ההגשות שלו.',
            'user_role_label': 'משתמש',
            'recruiter_role_label': 'מגייס',
            'admin_role_label': 'מנהל',
            'blocked_role_label': 'חסום',
            'active_status': 'פעיל',
            'blocked_status': 'חסום',
            'joined_date': 'הצטרף/ה ב:',
            'search_placeholder_users': 'חימוש לפי שם או אימייל...',
            'no_users_found': 'לא נמצאו משתמשים.',
            'previous': 'הקודם',
            'next': 'הבא',
            'page_of': 'מתוך',
            'page_title_users': 'משתמשים רשומים',

            // Job Manager & Application Viewer
            'job_postings': 'פרסום משרות',
            'total_jobs': 'משרות בסך הכל',
            'new_job': 'משרה חדשה',
            'no_jobs_found': 'אין משרות עדיין. צרו את המשרה הראשונה שלכם!',
            'edit_job': 'עריכת משרה',
            'create_new_job': 'יצירת משרה חדשה',
            'title_required': 'שם המשרה והתיאור הם שדות חובה',
            'title_label': 'כותרת המשרה *',
            'desc_label': 'תיאור המשרה *',
            'location_label': 'מיקום',
            'job_type_label': 'סוג משרה',
            'visibility_label': 'נראות באתר',
            'visible_opt': 'גלויה',
            'hidden_opt': 'מוסתרת',
            'edit_policy_label': 'מדיניות עריכה',
            'owner_only_opt': 'רק אני / מנהלים',
            'all_recruiters_opt': 'כל המגייסים',
            'transfer_ownership': 'העברת בעלות (מנהל בלבד)',
            'new_owner_placeholder': 'הזינו מזהה משתמש (User ID) של הבעלים החדש',
            'new_owner_help': 'ניתן להעתיק את מזהה המשתמש מלשונית משתמשים. השאירו ריק לשמירת הבעלים הנוכחי.',
            'cancel': 'ביטול',
            'save_changes': 'שמירת שינויים',
            'create_job_btn': 'צור משרה',
            'view_applications_title': 'הגשות עבור: ',
            'back_to_jobs': 'חזרה למשרות',
            'no_applications_found': 'אין הגשות עדיין למשרה זו.',
            'deleted_user_badge': 'משתמש מחוק',
            'view_cv': 'צפייה בקורות חיים',
            'cover_letter_label': 'מכתב מקדים:',
            'applied_date': 'תאריך הגשה: ',
            'pending_status': 'ממתין',
            'reviewed_status': 'נבדק',
            'accepted_status': 'התקבל',
            'rejected_status': 'נדחה',
            // Job Templates & Custom Fields
            'manage_templates': 'ניהול תבניות',
            'templates_title': 'תבניות משרות',
            'new_template': 'תבנית חדשה',
            'no_templates_found': 'אין תבניות משרות עדיין.',
            'create_template_btn': 'צור תבנית',
            'edit_template': 'עריכת תבנית',
            'create_new_template': 'יצירת תבנית חדשה',
            'template_label': 'בחר תבנית משרה (אופציונלי)',
            'template_title_label': 'שם התבנית *',
            'custom_fields_title': 'שדות מותאמים אישית',
            'add_custom_field': 'הוסף שדה',
            'field_label': 'שם השדה (למשל: שנות ניסיון)',
            'field_type': 'סוג השדה',
            'field_value': 'ערך השדה',
            'field_options': 'אפשרויות (מופרדות בפסיקים עבור רשימה)',
            'text_type': 'טקסט חופשי',
            'list_type': 'רשימה / בחירה',
            'candidate_questions_title': 'שאלות למועמד בהגשת מועמדות',
            'add_question': 'הוסף שאלה',
            'question_text_label': 'שאלה *',
            'question_type': 'סוג שאלה',
            'question_required': 'שדה חובה?',
            'text_question_type': 'תשובת טקסט חופשי',
            'checkbox_question_type': 'תיבת סימון (כן/לא)',
            'expiration_date_label': 'תאריך תפוגה של המשרה (אופציונלי)',
            'expired_badge': 'פג תוקף',
            'status_expired': 'פג תוקף',
            'extend_job': 'הארכת משרה',
            'close_job': 'סגירת משרה',
            'reopen_job': 'פתיחה מחדש',
        },
        en: {
            // Header
            'programs': 'Programs',
            'lets_talk': "Let's Talk",
            'mobile_menu': 'Menu',

            // Hero
            'hero_title': 'Barak Aloni',
            'hero_subtitle': 'Therapy Dog Workshops & Empowerment',
            'hero_description': 'Education, community, and organizations. Building an empowering, values-driven, and connecting experience together – with over 10 years of field experience.',
            'who_is_it_for': 'Who is it for?',
            'experience': '+10 Years Experience',
            'nationwide': 'Nationwide',
            'all_ages': 'All Ages & Populations',
            'video_title': 'Barak Aloni - Promotional Video',

            // Programs
            'our_programs': 'Our Programs',
            'tailored_solutions': 'Tailored Solutions',
            'for_education': 'For Education & Organizations',
            'program_education_title': 'Gefen / Educational Institutions',
            'program_education_content': 'A process-oriented program for students from 1st to 12th grade, adapted for regular education, special education, at-risk youth, new immigrants, and more. We provide a supportive and complementary response to the educational processes taking place within the school.',
            'program_events_title': 'Workshops & One-Time Events',
            'program_events_content': 'High-energy experiential activities suitable for: birthdays, summer camps, team-building workshops, and more! Our dogs and team bring joy, learning, and a sense of personal empowerment to all participants.',
            'program_special_title': 'Special Populations',
            'program_special_content': 'Dedicated adjustments for various populations such as: PTSD, elderly, at-risk youth, day centers, and more. We integrate empowering tools and group work that strengthens trust and a sense of security.',
            'more_details': 'More Details',
            'watch_video': 'Watch Video',

            // Contact
            'contact_title': 'Contact Us',
            'contact_subtitle': 'Want to hear more? \nWe are available for any question, consultation, or request.',
            'who_we_are': 'Who are you talking to?',
            'barak_aloni': 'Barak Aloni',
            'email': 'Email',
            'area': 'Activity Area',
            'follow_us': 'Follow Us',
            'full_name': 'Full Name',
            'phone_label': 'Phone',
            'email_label': 'Email',
            'message_optional': 'Message (Optional)',
            'message_placeholder': 'Hi, I would like to hear more details about...',
            'send_details': 'Send Details',
            'privacy_note': '* Data is sent directly to our email and not shared with third parties.',
            'whatsapp_message': 'I would like to hear more details about your services',
            'name_placeholder': 'John Doe',
            'phone_placeholder': '050-0000000',
            'email_placeholder': 'your@email.com',

            // Footer
            'accessibility_statement': 'Accessibility Statement',
            'privacy_policy': 'Privacy Policy',
            'copyright': '© All rights reserved to Barak Aloni {year}. Do not copy, duplicate, or photograph.',

            // Program Modal
            'program_modal_title': 'Gefen / Educational Institutions',
            'therapeutic_dog_training': 'Therapeutic Dog Training',
            'gefen_approved': 'Gefen Approved Program',
            'program_intro': 'This educational program combines the world of dog training with personal development. The program is designed to develop social skills, communication, and self-confidence in students.',
            'program_goals_title': 'Program Goals',
            'program_goal_1': 'Personal and Group Empowerment',
            'program_goal_1_desc': 'Through experiential work, where dogs act as a mirror for life itself, students develop a sense of capability, build a positive self-image, and learn to work cooperatively.',
            'program_goal_2': 'Acceptance of Others and Self-Acceptance',
            'program_goal_2_desc': 'The dog accepts every student unconditionally and without judgment, allowing students to learn to accept themselves and others in a supportive environment.',
            'program_goal_3': 'Strengthening and Developing Life Skills',
            'program_goal_3_desc': 'The program imparts crucial skills such as patience, setting boundaries, and personal responsibility that translate into everyday classroom life.',
            'program_goal_4': 'Overcoming Fears',
            'program_goal_4_desc': 'The gradual and guided encounter with the dogs provides students with a safe environment to confront personal fears and barriers.',
            'program_goal_5': 'Strengthening Social Involvement',
            'program_goal_5_desc': 'Group work creates a sense of belonging, encourages mutual help, and leads to more active and positive involvement in school life.',
            'program_goal_6': 'Social Connection in the School Environment',
            'program_goal_6_desc': 'Dogs act as a bridge for creating social connections between students, helping them collaboratively overcome social and emotional challenges.',
            'program_targets_title': 'Goals and Values',
            'program_target_1': 'Creating a Safe Educational Environment',
            'program_target_2': 'Non-Judgmental Discussions',
            'program_target_3': 'Expressing Opinions Without Fear',
            'program_target_4': 'Taking Personal Responsibility',
            'program_target_5': 'Participation by Choice and Will',
            'target_audience_title': 'Target Audience',
            'target_audience_content': 'The program is intended for students from <span className="font-bold text-gray-900">1st to 12th grade</span> from all sectors. \nAdapted for a wide range of populations: gifted, special education, at-risk youth, attention disorders, learning disabilities, new immigrants, etc.',
            'methods_title': 'Methods',
            'methods_content_1': 'Through the world of dogs, we learn effective communication, body language, basic training, dog sports, and service dogs. The training is conducted "at eye level" while creating trust and mutual commitment.',
            'methods_content_2': 'Groups are fixed (without changing students) to maintain a safe and intimate space. We perform personal monitoring of each student to refine the response.',
            'expected_results_title': 'Expected Results',
            'result_1': 'Self and Social Confidence',
            'result_2': 'Creating Social Connections',
            'result_3': 'Developing Empathy and Compassion',
            'result_4': 'Morality Towards Animals',
            'technical_details_title': 'Technical Details:',
            'group_size': '• Group Size: 6-8 Students',
            'requirements': '• Requirements: Fixed classroom, educational counselor accompaniment',
            'contact_details_modal': '• Contact: Barak Aloni | 050-8391268 | Dogs@barakaloni.com',

            // Accessibility Widget
            'accessibility_tools': 'Accessibility Tools',
            'grayscale': 'Grayscale',
            'invert_contrast': 'Invert Contrast',
            'decrease_text': 'Decrease Text',
            'increase_text': 'Increase Text',
            'highlight_headings': 'Highlight Headings',
            'highlight_links': 'Highlight Links',
            'readable_font': 'Readable Font',
            'big_cursor': 'Big Cursor',
            'stop_animations': 'Stop Animations',
            'reset_settings': 'Reset Settings',

            // Cookie Banner
            'cookies_title': 'We Use Cookies',
            'cookies_text': 'This site uses cookies to improve your browsing experience. Continuing to browse the site constitutes acceptance of this use.',
            'learn_more': 'Learn More',
            'got_it': 'Got It, Thanks',

            // Legal Modal
            'legal_info': 'Legal Information',
            'accessibility_intro': 'At Barak Aloni, we view equal service for all customers and visitors as paramount and strive to improve service for customers with disabilities.',
            'accessibility_resources': 'Accordingly, we invest significant resources in making our site accessible to allow the majority of the population to browse it easily and comfortably.',
            'accessibility_level': 'Accessibility Level',
            'accessibility_standard': 'The site is built in accordance with the Equal Rights for Persons with Disabilities Regulations (Service Accessibility Adjustments), 2013, and Israeli Standard 5568 for Web Content Accessibility at Level AA.',
            'adjustments_made': 'Adjustments Made',
            'adjustment_1': 'The site is adapted for viewing in common browsers (Chrome, Firefox, Safari, Edge).',
            'adjustment_2': 'Site content is written in clear and legible language.',
            'adjustment_3': 'Site structure is based on clear and convenient navigation and menus built using lists allowing easy orientation.',
            'adjustment_4': 'The site is adapted for mobile browsing (responsive).',
            'adjustment_5': 'Images on the site include alternative textual description (Alt Text).',
            'adjustment_6': 'The site allows font size change using the keyboard (Ctrl + / -).',
            'accessibility_contact_title': 'Contact Regarding Accessibility',
            'accessibility_contact_text': 'If you encountered any difficulty browsing the site or have a comment on the subject, we would be happy if you contacted us so we can handle the problem:',
            'accessibility_email': 'Email: dogs@barakaloni.com',
            'accessibility_phone': 'Phone: 050-8391-268',
            'privacy_intro': 'We respect the privacy of site users and are committed to protecting the personal information you share with us.',
            'data_collection': 'Data Collection',
            'data_collection_text': 'When you leave details on the site (name, phone, email) for the purpose of contact, we collect this information solely for the purpose of getting back to you and providing service.',
            'data_use': 'Use of Information',
            'data_use_text': 'The information collected will not be transferred to third parties without your consent, unless we are required to do so by law.',
            'cookies_policy_title': 'Cookies',
            'cookies_policy_text_1': 'The site may use "Cookies" for its ongoing and proper operation, including to collect statistical data about site usage, for details verification, and to adapt the site to your personal preferences.',
            'cookies_policy_text_2': 'Modern browsers allow you to avoid receiving Cookies. If you do not know how to do this, check the help file of the browser you are using.',
            // User Menu
            'profile': 'Profile',
            'my_applications': 'My Applications',
            'admin_dashboard': 'Admin Dashboard',
            'recruiter_dashboard': 'Recruiter Dashboard',
            'sign_out': 'Sign Out',
            'admin_role': 'Admin',
            'recruiter_role': 'Recruiter',

            // Manager & Dashboard Translations
            'mission_control': 'Mission Control',
            'analytics_dashboard_sub': 'Analytics Dashboard',
            'uptime': 'Uptime',
            'home_website': 'Home Website',
            'all_pages': 'All Pages',
            'online': 'online',
            'overview': 'Overview',
            'traffic': 'Traffic',
            'content': 'Content',
            'geo': 'Geo & Devices',
            'feed': 'Live Feed',
            'jobs': 'Jobs',
            'users': 'Users',
            'unique_30d': 'Unique (30d)',
            'views_24h': 'Views (24h)',
            'videos_24h': 'Videos (24h)',
            'contacts_24h': 'Contacts (24h)',
            'whatsapp_24h': 'WhatsApp (24h)',
            'conversion_funnel': 'Conversion Funnel',
            'funnel_sub': '30-day visitor journey',
            'visitors': 'Visitors',
            'video_plays': 'Video Plays',
            'contact_clicks': 'Contact Clicks',
            'whatsapp': 'WhatsApp',
            'form_submits': 'Form Submits',
            'traffic_growth': 'Traffic Growth',
            'traffic_sub': 'Unique vs Total (30 Days)',
            'page_views': 'Page Views',
            'unique_people': 'Unique People',
            'peak_hours': 'Peak Hours',
            'peak_hours_sub': 'When visitors arrive',
            'by_day_of_week': 'By Day of Week',
            'per_page_traffic': 'Per-Page Traffic',
            'per_page_sub': 'Daily visits by page (30 days)',
            'source_trends': 'Source Trends',
            'source_trends_sub': 'Where traffic comes from (Daily)',
            'return_vs_new': 'Return vs New Visitors',
            'return_vs_new_sub': 'Daily breakdown (30 days)',
            'new': 'New',
            'returning': 'Returning',
            'top_sources_30d': 'Top Sources (30d)',
            'direct_bookmark': 'Direct / Bookmark',
            'no_data_yet': 'No data yet.',
            'utm_campaigns_90d': 'UTM Campaigns (90d)',
            'no_utm_data': 'No UTM data yet. Add ?utm_source=... to your links.',
            'video_views': 'Video Views',
            'no_video_data': 'No video play data yet',
            'video_data_sub': 'Video play events will appear here as individual charts once visitors start watching videos.',
            'scroll_depth': 'Scroll Depth',
            'scroll_depth_sub': 'Avg % scrolled per page',
            'time_per_page': 'Time Per Page',
            'time_per_page_sub': 'Avg session duration',
            'lang_bounce': 'Language & Bounce',
            'bounce_by_page': 'Bounce Rate by Page',
            'contact_channels': 'Contact Channels',
            'contact_channels_sub': 'WhatsApp vs Contact clicks',
            'top_content': 'Top Content',
            'top_countries': 'Top Countries',
            'visitor_origins_sub': '30-day visitor origins',
            'top_cities': 'Top Cities',
            'devices_browsers': 'Devices & Browsers',
            'device_sub': 'Device breakdown (Desktop/Mobile)',
            'browsers': 'Browsers',
            'operating_systems': 'Operating Systems',
            'activity_log': 'Activity Log',
            'activity_sub': 'Real-time action stream',
            'all_events': 'All Events',
            'no_logs': 'No logs available.',

            // User Roles
            'role_guidelines_title': 'User Roles Guidelines',
            'role_guidelines_sub': 'Quick reference of system roles and their permissions:',
            'role_admin_desc': 'Full permissions. Can view site analytics, manage registered users and their roles, block/unblock accounts, create/edit jobs, and review/manage all applications.',
            'role_recruiter_desc': 'Recruitment permissions. Can create and edit job postings, and review candidates who applied for those jobs. No access to site analytics or the user directory.',
            'role_user_desc': 'Job seeker or guest. Can browse the job board, submit applications, upload a resume (CV), manage their own profile, and track their application status.',
            'user_role_label': 'User',
            'recruiter_role_label': 'Recruiter',
            'admin_role_label': 'Admin',
            'blocked_role_label': 'Blocked',
            'active_status': 'Active',
            'blocked_status': 'Blocked',
            'joined_date': 'Joined:',
            'search_placeholder_users': 'Search by name or email...',
            'no_users_found': 'No users found.',
            'previous': 'Previous',
            'next': 'Next',
            'page_of': 'of',
            'page_title_users': 'Registered Users',

            // Job Manager & Application Viewer
            'job_postings': 'Job Postings',
            'total_jobs': 'total jobs',
            'new_job': 'New Job',
            'no_jobs_found': 'No jobs yet. Create your first job posting!',
            'edit_job': 'Edit Job',
            'create_new_job': 'Create New Job',
            'title_required': 'Title and description are required',
            'title_label': 'Title *',
            'desc_label': 'Description *',
            'location_label': 'Location',
            'job_type_label': 'Job Type',
            'visibility_label': 'Visibility',
            'visible_opt': 'Visible',
            'hidden_opt': 'Hidden',
            'edit_policy_label': 'Edit Policy',
            'owner_only_opt': 'Only Me / Admins',
            'all_recruiters_opt': 'All Recruiters',
            'transfer_ownership': 'Transfer Ownership (Admin Only)',
            'new_owner_placeholder': 'Enter New Owner User ID',
            'new_owner_help': 'Get the User ID from the Users tab. Leave blank to keep current owner.',
            'cancel': 'Cancel',
            'save_changes': 'Save Changes',
            'create_job_btn': 'Create Job',
            'view_applications_title': 'Applications for: ',
            'back_to_jobs': 'Back to Jobs',
            'no_applications_found': 'No applications yet for this job.',
            'deleted_user_badge': 'Deleted User',
            'view_cv': 'View CV',
            'cover_letter_label': 'Cover Letter:',
            'applied_date': 'Applied: ',
            'pending_status': 'Pending',
            'reviewed_status': 'Reviewed',
            'accepted_status': 'Accepted',
            'rejected_status': 'Rejected',
            // Job Templates & Custom Fields
            'manage_templates': 'Manage Templates',
            'templates_title': 'Job Templates',
            'new_template': 'New Template',
            'no_templates_found': 'No job templates found yet.',
            'create_template_btn': 'Create Template',
            'edit_template': 'Edit Template',
            'create_new_template': 'Create New Template',
            'template_label': 'Select Job Template (Optional)',
            'template_title_label': 'Template Title *',
            'custom_fields_title': 'Custom Fields',
            'add_custom_field': 'Add Field',
            'field_label': 'Field Label (e.g. Years of Experience)',
            'field_type': 'Field Type',
            'field_value': 'Field Value',
            'field_options': 'Options (comma-separated for dropdown)',
            'text_type': 'Free Text',
            'list_type': 'Dropdown List',
            'candidate_questions_title': 'Candidate Application Questions',
            'add_question': 'Add Question',
            'question_text_label': 'Question *',
            'question_type': 'Question Type',
            'question_required': 'Required?',
            'text_question_type': 'Free Text Answer',
            'checkbox_question_type': 'Checkbox (Yes/No)',
            'expiration_date_label': 'Job Expiration Date (Optional)',
            'expired_badge': 'Expired',
            'status_expired': 'Expired',
            'extend_job': 'Extend Job',
            'close_job': 'Close Job',
            'reopen_job': 'Reopen Job',
        }
    };

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => prev === 'he' ? 'en' : 'he');
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
